spring.application.name=parking-management-service
spring.datasource.url=jdbc:postgresql://localhost:5432/parqueadero_db
spring.datasource.username=postgres
spring.datasource.password=1234

server.port=8090
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=bWlfY2xhdmVfc2VjcmV0YV9zdXBlcl9zZWd1cmFfMTIzNDU2
security.jwt.expiration-ms=86400000