package com.coding.parkingmanagementservice.shared.exception;

public enum ErrorCode {
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    USER_NOT_FOUND,
    INVALID_EMAIL,
    INVALID_PASSWORD,

    VALIDATION_ERROR,
    BAD_CREDENTIALS,
    INTERNAL_SERVER_ERROR,

    PLACA_CON_INGRESO_ACTIVO,
    INGRESO_NO_ENCONTRADO,
    TIPO_VEHICULO_NO_ENCONTRADO,
    UBICACION_NO_ENCONTRADA,
    UBICACION_NO_DISPONIBLE,
    UBICACION_OCUPADA,
    TIPO_VEHICULO_INCOMPATIBLE_CON_UBICACION,
    ESTADO_INGRESO_NO_ENCONTRADO,
    USUARIO_AUTENTICADO_NO_ENCONTRADO,
    ROL_NO_ENCONTRADO,
    ESTADO_USUARIO_NO_ENCONTRADO,
    ACCION_NO_PERMITIDA,

    TARIFA_NO_ENCONTRADA,
    TARIFA_UNIDAD_NO_ENCONTRADA,
    UBICACION_CON_INGRESOS_ACTIVOS
}